### PR TITLE
Auth Pages Integration with API

### PR DESCRIPTION
**Pull request by bajajcodes**
## Auth Page
- User can login, signup and do guest login.
- For api calls custom hook useAxios is used.
- For form input custom local hook useForm is used.
- Alerts and Loader are not made available, but validation and error handling is done.
(For confirmation check console log)
- Token is stored on local storage during signup and login, to persist login during page 
   refresh and removed on logout.
- Auth context is used to get and set login status and make it available globally.
- Context wrapper is used for making all contexts encapsulated at once place and improving readability.

## Suggestion
- Check auth functionality and redirects on auth pages(if logged in, not done for other pages).

## Deploy Preview
https://deploy-preview-4--3on3tube.netlify.app/

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
your code is well structured and naming is also good .

**Review by tanishk15sharma — APPROVED** [review]
you can merge this PR

**Review by srishtigautam21 — APPROVED** [review]
Neatly structured code
The UI also looks great
Good work
Good to merge

**Review by GuptaEesh — COMMENTED** [review]
- Could see good use of optional chaining and bullish coalescing.
- Good that you provided guest login feature.
Good to merge

**Review by sri-rishi — APPROVED** [review]
Code looks clean and structured , you can merge this pr

**Pull request merged**
